name: .NET Core - Release

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    nuget:
        name: Publish Dev Package
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4.1.7
            -   uses: actions/setup-dotnet@v4.0.1
                with:
                    dotnet-version: 8.x
            -   id: git-vars
                name: Set up environment
                shell: bash
                run: |
                    echo "##[set-output name=git_branch;]$(echo $GITHUB_REF)"
                    echo "::set-output name=git_hash::$(git rev-parse --short HEAD)"
            -   id: set-vars
                uses: actions/github-script@v7.0.1
                with:
                    script: |
                        let gitHash = "${{ steps.git-vars.outputs.git_hash }}";
                        let runNumber = "${{ github.run_number }}"; 
                        let rawGitRef = "${{ steps.git-vars.outputs.git_branch }}";
                        console.log("rawGitRef: " + rawGitRef);
                        let gitRef = rawGitRef.replace(/^refs\/heads\//, "");
                        if(gitRef.indexOf("refs/pull/") === 0) {
                          gitRef = "pr-" + gitRef.substring(10, gitRef.lastIndexOf("/"));
                        }
                        var versString = `${gitRef}.${runNumber}+${gitHash}`;
                        console.log(versString);
                        core.setOutput("versionString", versString);
            -   name: Install dependencies
                run: dotnet restore /p:VersionSuffix=${{ steps.set-vars.outputs.versionString }}
            -   name: Build all
                run: dotnet build -c Release /p:VersionSuffix=${{ steps.set-vars.outputs.versionString }}
                working-directory: Disarm.Tests
            - name: Upload Disarm
              uses: actions/upload-artifact@v4
              with:
                name: Disarm
                path: ./Disarm/bin/Release/*
